# Generated by Django 4.2.4 on 2023-08-31 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("dosage", models.CharField(max_length=20)),
                ("quantity", models.SmallIntegerField(blank=True, null=True)),
                ("times_taken", models.SmallIntegerField(help_text="Times taken per day.")),
                ("refills", models.SmallIntegerField(blank=True, null=True)),
                ("prescriber", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["name", "user"], name="medication_name_user_idx")],
            },
        ),
    ]
